# Generated by Django 5.2.6 on 2025-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título do banner (para identificação no admin)",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagem do banner",
                        upload_to="banners/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("collections_stats", "Estatísticas das Coleções"),
                            ("hero", "Banner Principal"),
                            ("promotional", "Promocional"),
                            ("announcement", "Anúncio"),
                        ],
                        default="collections_stats",
                        help_text="Tipo de banner para determinar onde será exibido",
                        max_length=50,
                        verbose_name="Tipo de Banner",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o banner está ativo e deve ser exibido",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição (menor número aparece primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
