# Generated by Django 5.2.6 on 2025-10-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="banner_type",
        ),
    ]
