# Generated by Django 5.2.6 on 2025-10-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0002_remove_banner_banner_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="image",
        ),
        migrations.AddField(
            model_name="banner",
            name="image_url",
            field=models.URLField(
                default="https://via.placeholder.com/800x300/FFE000/000000?text=Banner+Placeholder",
                help_text="URL da imagem do banner (ex: https://exemplo.com/imagem.jpg)",
                max_length=500,
                verbose_name="URL da Imagem",
            ),
        ),
    ]
