# Generated by Django 5.2.6 on 2025-09-23 17:45

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=42, unique=True, validators=[gallery.models.validate_eth_address])),
                ('icon_url', models.URLField(blank=True)),
                ('collection_image_url', models.URLField(blank=True)),
                ('metadata_api_url', models.URLField(blank=True)),
                ('project_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('project_owner_address', models.CharField(blank=True, max_length=42, validators=[gallery.models.validate_eth_address])),
                ('website_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='gallery_nft_slug_90a8c8_idx'), models.Index(fields=['address'], name='gallery_nft_address_d1967d_idx')],
            },
        ),
    ]
