# Generated by Django 5.2.6 on 2025-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_refactor_collection_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nftcollection",
            name="cover_image",
            field=models.URLField(blank=True, verbose_name="Foto de Capa"),
        ),
        migrations.AlterField(
            model_name="nftcollection",
            name="profile_image",
            field=models.URLField(blank=True, verbose_name="Foto de Perfil"),
        ),
    ]
