services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["/bin/sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8001:8000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      # Browser will hit the mapped host port
      - VITE_API_BASE_URL=http://localhost:8001
      - PORT=5173
    ports:
      - "5173:5173"
    depends_on:
      web:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  celery_worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["/bin/sh", "-c", "celery -A core worker -l info -Q celery,default -n worker1@%h -E"]
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_beat:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: ["/bin/sh", "-c", "celery -A core beat -l info --schedule=/app/celerybeat-schedule/celerybeat-schedule"]
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - celerybeat:/app/celerybeat-schedule
    restart: unless-stopped

  flower:
    image: mher/flower:2.0.1
    ports:
      - "5555:5555"
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  celerybeat: