name: Test YAML Syntax

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test YAML
        run: |
          echo "Testing YAML syntax..."
          python3 -c "
          import yaml
          try:
              with open('.github/workflows/deploy-aws.yml', 'r') as f:
                  yaml.safe_load(f)
              print('✅ YAML syntax is valid')
          except yaml.YAMLError as e:
              print(f'❌ YAML syntax error: {e}')
              exit(1)
          except Exception as e:
              print(f'❌ Error: {e}')
              exit(1)
          "
