name: Test Deploy AWS - Simplified

on:
  workflow_dispatch:  # Permite execução manual
  push:
    branches: [ "main" ]

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: nft-portal

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test YAML syntax
        run: |
          echo "Testing YAML syntax..."
          python -c "import yaml; yaml.safe_load(open('.github/workflows/deploy-aws.yml', 'r')); print('✅ YAML syntax is valid')"
        continue-on-error: true

      - name: Check secrets
        run: |
          echo "=== Checking secrets ==="
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID != '' && 'SET' || 'NOT SET' }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST != '' && 'SET' || 'NOT SET' }}"
          echo "SECRET_KEY: ${{ secrets.SECRET_KEY != '' && 'SET' || 'NOT SET' }}"

      - name: Test AWS connection
        if: secrets.AWS_ACCESS_KEY_ID != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS
        if: secrets.AWS_ACCESS_KEY_ID != ''
        run: |
          echo "Testing AWS connection..."
          aws sts get-caller-identity
          echo "✅ AWS connection successful"

      - name: Summary
        run: |
          echo "🎉 Test completed!"
          echo "If all steps passed, the main deploy workflow should work."
